-- Auto-install packages

--[[ local mason_registry = require("mason-registry")

local mason_packages = {
	"astro-language-server",
	"bash-debug-adapter",
	"bash-language-server",
  "blade-formatter",
	"buf",
  "buf-language-server",
	"cbfmt",
	"chrome-debug-adapter",
  "clangd",
  "clang-format",
	"codelldb",
	"css-lsp",
	"dart-debug-adapter",
	"delve",
	"deno",
  "docker-compose-language-service",
	"dockerfile-language-server",
	"editorconfig-checker",
	"eslint_d",
	"firefox-debug-adapter",
	"gopls",
	"gradle-language-server",
	"graphql-language-service-cli",
	"html-lsp",
  "intelephense",
	"json-lsp",
	"jsonlint",
	"kotlin-debug-adapter",
	"kotlin-language-server",
	"lua-language-server",
	"markdownlint",
  "misspell",
  "nginx-language-server",
	"node-debug2-adapter",
	"omnisharp",
  "phpactor",
	"prettierd",
	"prisma-language-server",
  "proselint",
	"protolint",
  "python-lsp-server",
	"rust-analyzer",
	"shfmt",
	"sql-formatter",
	"sqlfluff",
	"sqlls",
	"stylua",
	"svelte-language-server",
	"tailwindcss-language-server",
	"taplo",
  "terraformls",
  "tflint",
  "tfsec",
	"typescript-language-server",
	"vim-language-server",
	"vue-language-server",
  "write-good",
	"yaml-language-server",
	"yamlfmt",
	"yamllint",
}

for _, mason_package in pairs(mason_packages) do
	if not mason_registry.is_installed(mason_package) then
		mason_registry.get_package(mason_package):install({ version = "latest" })
	end
end ]]
