import = ["~/.config/alacritty/rose-pine.toml"]

shell.program = "/bin/zsh"
shell.args = ["--login"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 0.95
padding.x = 0
padding.y = 0

[font]
normal.family = "JetBrains Mono Nerd Font"
size = 13.0

[colors.primary]
background = "#0C0D18"
